services:
  mysql:
    image: mysql:8.0
    container_name:  django_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - django-net

volumes:
  mysql_data:
    name: django_mysql_data

networks:
  django-net:
    driver: bridge